fastlane_version "2.53.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(
      api_token: System.getenv("CRASHLYTICS_API_TOKEN"),
      build_secret: System.getenv("CRASHLYTICS_BUILD_SECRET")
    )

    # upload to HockeyApp
    hockey(
      api_token: System.getenv("HOCKEY_API_TOKEN")
    )

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
