fastlane_version "2.53.0"

default_platform :android

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :supply_data do
    gradle(task: "assembleRelease")
    gradle(task: "assembleAndroidTest")
    supply(
        skip_upload_apk: true
    )
  end

end
